apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: gcr.io/$PROJECT_ID/gcp-poc/helloworld-image:latest
        ports:
        - containerPort: 8080
